### ISSUE TITLE
Data type of created column does not include date

### ISSUE THREAD

**Issue by fwise** [YoloDev/elephanet#17]
The created column uses the data type "time without time zone"

    created time without time zone NOT NULL DEFAULT now()

Would it be more appropriate to include the date as well as use utc?

    created timestamp without time zone NOT NULL default (now() at time zone 'utc')

https://github.com/YoloDev/elephanet/blob/master/Elephanet/DocumentSession.cs#L216

**Comment by jmkelly** [comment]
Nice catch.  Fixed in https://github.com/YoloDev/elephanet/commit/a52a6dafbfcaa7dcf16211f7ba657addd6c97a43

**Comment by jmkelly** [comment]
and then *properly* fixed in https://github.com/YoloDev/elephanet/commit/556b5aa737050c7be69e7127f37b014cbcef47ab
