### ISSUE TITLE
id and created are not populated in LoadInternal

### ISSUE THREAD

**Issue by fwise** [YoloDev/elephanet#18]
When retrieving an entity by Id, the Id and Created fields are not populated.  Elephanet requires Id but does not require a Created datetime.  Perhaps it would only hydrate Created if it existed on the entity.  I'd most likely just stick it on an Entity base class.  (Should the same thing be done for row version number as well?)   failing test pseudo below

https://github.com/YoloDev/elephanet/blob/556b5aa737050c7be69e7127f37b014cbcef47ab/Elephanet/DocumentSession.cs#L73-L94

```c#
var user = new User()
{
    FirstName = "Johnny",
    LastName = "Appleseed"
};

using (var session = _documentStore.OpenSession())
{
    session.Store(user);
    session.SaveChanges();
}

using (var session = _documentStore.OpenSession())
{
    var john = session.GetById<User>(user.Id);         
    john.Id.Should().NotBeEmpty();
    john.Created.Should().NotBe(DateTime.Empty);
}
```

**Comment by fwise** [comment]
I was partially wrong with this issue but surfaced some other interesting behavior.

The JilJsonSerializer does not appear to serialize inherited properties by default.  I'm using an entity base class with Guid Id {get;set;}.  This does not end up in the table's body column and is therefore not deserialized out.  

The question is: should the Id be serialized into the body column or is the id column sufficient.  It will have to be explicitly queried out and set on the object if it is not in the jsonb body.

**Comment by jmkelly** [comment]
Looks like Jil has a option setting, and doesn't serialize inherited members when serializing, so that's why you are seeing this.  The Id *should* be serialized into the body, so this option just needs to be flicked.

**Comment by jmkelly** [comment]
Fixed in https://github.com/YoloDev/elephanet/commit/2e4fcd9d250a504dbadf335f8f0f9fb3347fd873
