### ISSUE TITLE
DateTime issues with default serializer

### ISSUE THREAD

**Issue by fwise** [YoloDev/elephanet#19]
Jil blows up when deserializing DateTime.

This can be demonstrated by adding a DateTime prop to Car in the Tests project and running the tests. 

One guess is that the customized Options being passed into JSON.Serialize also need to be passed into Deserialize.

**Comment by jmkelly** [comment]
I haven't got a chance to look at the moment, but I'd say you are right. Feel free to send a pr if I can't get to it fast enough for you.

**Comment by fwise** [comment]
ok no problem. I'll try to knock this out.

On another note, the default DateTime format is newtonsoft ms since unix epoch. I'd guess that ISO8601 would be preferred by most and its lead me to my own impl of IJsonConverter (plus I needed to get around this current #19). Just something to think about.

**Comment by jmkelly** [comment]
I agree that ISO would certainly be preferable.  I think the date format may also be a reason why the tests fail with a datetime, as the serializer handles it fine, so perhaps postgres is doing something to the datetime string when saving to jsonb format.

If we find too many issues with Jil, I'm not against providing some sort of extension, one for Jil (for speed) and one for Json.Net when you need more options supported.

**Comment by jmkelly** [comment]
Just tested, it's the dateformat that is causing the serializing -> deserializing to fail.  Switched to ISO8601 (which I think is a much better default), and it all passes again.  Thanks for picking this up.

**Comment by fwise** [comment]
Thanks for getting to this. I had noticed the same behavior. The speed of Jil is appealing but one of my future concerns is that it doesn't guarantee/provide any ordering in the JSON.
