### ISSUE TITLE
IdentityFactory - potential threading issues

### ISSUE THREAD

**Issue by fwise** [YoloDev/elephanet#23]
I'm seeing some behavior in some XUnit tests (this is basically how I am auditing this lib) that indicate some threading/race conditions when accessing the IdentityFactory.  I'm guessing the access to the static Dictionary is the cause.

  -  My assumption is that a single DocumentStore could be created per application and that the DocumentSessions were the "unit of work".
  -  I think the Elephanet tests do not expose this issue because the parallelization Xunit does is at the fixture level (not Fact) and each test fixture creates its own DocumentStore.

Will post more detail but wanted to get this out there.

**Comment by fwise** [comment]
Just noticed too that I am using Xunit 2.0 which parallelizes tests by default. Appears elephanet is using an older version.

**Comment by fwise** [comment]
I've been able to verify this issue by updating the Elephanet Tests to use XUnit 2 and then updating the  test fixtures to use a shared DocumentStore.   I think I have identified 2 non thread-safe areas.

1. IdentityFactory.TryGetIdProperty,  Its static Dictionary is accessed in DocumentSession's across threads.
2. StoreInfo.Tables (HashSet<string>). Instance member on DocumentStore and read/write to via DocumentSession.

ConcurrentDictionarys would probably be the quick fix.

**Comment by jmkelly** [comment]
Any chance you could push through the update to xunit and the shared store tests? To be honest, multithreading is not a strong suit of mine, so I'm more than happy to let you take the lead on this one, and if all that is required is a switch to concurrent dictionary to get the tests to pass, I'm happy with that.  You're assumption lines up with my thinking in that the store is application scoped, and sessions are the unit of work.

If you find holes in the test cases, happy to accept more in, as long as the test suit time doesn't blow out exponentially.

**Comment by fwise** [comment]
Ok no worries, I have a pull request incoming.  It touches a lot of files (in Tests) because of the need to have a global TestStore.  The commit message will explain more.  I didn't add any additional tests nor any fixes.  Given these are threading issues, they don't happen every test run.  I'd have to run the test suite a few times to see some test fail but the tests failing were random and the same issue.

I did work around this in my local test suite by "touching" every entity at startup and essentially warming the non-threadsafe collections.  I have a marker interface on each entity/aggregate so this was easy to do.  In theory, that could be done in an app's bootstrapping code.  The heavier ORM's do a lot of this stuff in their initialization.  Alternatively, we can just make the collection access thread-safe. :)

**Comment by jmkelly** [comment]
closed with https://github.com/YoloDev/elephanet/pull/26
