### ISSUE TITLE
concurrency checking

### ISSUE THREAD

**Issue by tim-cools** [YoloDev/elephanet#29]
I want to implement concurrency checking to ensure that rows are not updated by another process when updating a record. I guess you planned to use the 'timestamp' column for this. Or is this a correct? Or is this a wrong assumption? Is it ok if I implement the check by using this field? Or did you plan something yourself in the near future?

What is the reason that you store inserts/updates in a temporary table first on a SaveChanges?

**Comment by jmkelly** [comment]
To be honest, the timestamp was left over from code I ripped off from elsewhere, and I'd never got around to removing.

Is what you're planning generally called optimistic concurrency? I have been thinking about it, but I haven't had much time to research fully. I believe postgres has settings that can force different consistency models, so I be looking into that before implementing something client side, but I realise we may not be able to avoid it given the unit of work is client side. Happy for you to have a look into it though, its not something I'm working on at the moment.

As for the update from temporaray tables, this was designed for upsert capabilities prior to postgresql 9.5 (which has upsert included), as detailed at http://stackoverflow.com/questions/17267417/how-do-i-do-an-upsert-merge-insert-on-duplicate-update-in-postgresql.
