### ISSUE TITLE
Enhancement: Make table naming strategy configurable

### ISSUE THREAD

**Issue by fwise** [YoloDev/elephanet#9]
Hi. This project is very intriguing and I hope to see it get some momentum. Thanks for the work so far.

While playing around with the nuget, I noticed that TableInfo class that can be provided via IStoreConvention does not really give you much. At this point you can only configure the schema. Ideally I think this would be more of an interface that allowed the consumer complete control over how table names are created.  The default convention based on the type name and namespace is convenient but brittle.  I'm interested in taking a shot at a more configurable option.  Did you have any ideas along this line or perhaps know how RavenDB does it.

Thanks.

**Comment by jmkelly** [comment]
You are 100% right, the TableInfo (or more correctly ITableInfo) should be injected into the IStorageConvention implementation, allowing the user far more control over how their tables are named. If the default is brittle though, I'd also be interested in the use case so we can work out something more appropriate.

I have not checked how other libraries do it, as I just hacked this convention out and moved on quickily, so I'm all ears on other options. Let us know your ideas, then you are more than welcome to fix my shoddy effort. Thanks for your interest!

**Comment by fwise** [comment]
Thanks for getting back quickly. To clarify, I meant brittle in the sense that because the table name is coupled to the namespace and type, you could easily break things by simply moving your type to a different namespace (esp in the case of deployment into an existing environment).  Truth be told though, I don't know if there's a better alternative in the default case.  It's really nice the way the current default is low touch.

I think to start, I'd just go down the path of what you are thinking with an ITableInfo interface, exposing the two naming methods that take Type as parameter and leaving it entirely to the consumer to dictate their impl.  Eventually you could provide some built-in implementations following a certain strategy.  For example, my implementation will be essentially custom string per Type and I'd probably have some builder/fluent way of building it.  I'd probably store the Type->string mappings in a Dictionary.

A heavier-handed route might be to have an interface per type override similar to what FluentNHibernate.

**Comment by jmkelly** [comment]
>I think to start, I'd just go down the path of what you are thinking with an ITableInfo interface, exposing the two naming methods that take Type as parameter and leaving it entirely to the consumer to dictate their impl

This is in line with my thinking, keep it simple to start.  Happy for you to tackle this, let us know if you have any issues.

**Comment by jmkelly** [comment]
Thanks @fwise , and hat tip for including tests (and a bug fix as well) https://github.com/YoloDev/elephanet/pull/16
